### ISSUE TITLE
NSKeyValueChangeKey should need iOS10 or later??

### ISSUE THREAD

**Issue by gongqiuwei** [facebook/KVOController#127]
in FBKVOController.h file:
typedef void (^FBKVONotificationBlock)(id _Nullable observer, id object, NSDictionary<NSKeyValueChangeKey, id> *change);

the  NSKeyValueChangeKey in XCode7.2 can not support
<img width="724" alt="2017-03-13 10 43 26" src="https://cloud.githubusercontent.com/assets/3827831/23839567/f44c9956-07d9-11e7-801a-0c00cbfc020b.png">

**Comment by drkibitz** [comment]
Any reason you are still using 7.2? This is not a condescending remark, really wondering.

**Comment by gongqiuwei** [comment]
my point is that NSKeyValueChangeKey is need iOS10+, so how could i use FBKVOController in my project to support iOS7+??, so i make this issue

**Comment by drkibitz** [comment]
Same question though, I know the new SDK has dropped 7 support. If it's not appropriate to answer in this forum that's fine, just curious is all. Sorry, I'm not the appropriate person to answer your question though, I can only assume this library inadvertently dropped iOS 7 support by including that typedef and probably others since.

**Comment by nlutsenko** [comment]
@gongqiuwei, I would recommend actually using the previous version of KVOController 1.1.0,
which supports Xcode 7.2 and should work without a hassle.

Going forward, since it's technically very hard to support both old and new SDKs in terms of features of the language and latest SDK available - we are going to support Xcode 8.0+ only.

Please note, this means that we also are going to support the lowest minimum deployment target supported by that version of Xcode. For Xcode 8 - it means iOS 8.0, tvOS 10.0, watchOS 1.0 and macOS 10.8 (we technically can support 10.7 and 10.6, but since we can't quite test on those in a fast or reliable manner - whether it works or not is `undefined`).
