### ISSUE TITLE
Passing in `self` as the observed object creates a retain cycle

### ISSUE THREAD

**Issue by gmaletic** [facebook/KVOController#29]
I notice that if I pass `self` in as the observed object, like so:

```
[self.kvo observe:self keyPath:@"widgets" options:NSKeyValueObservingOptionInitial block:^(id observer, id object, NSDictionary* change)
{
    // Some code here.
}
```

...a retain cycle is created. Checking in the `FBKVOController` source, I notice the `NSMapTable` you store observed objects in retains them. Is this required? Can it be set to use weak references?

**Comment by pronebird** [comment]
@grp with KVO you can observe like 20 properties at once. Having 20 setters is usually more code. I tried using KVOControllerNonRetaining but it tends to crash in all kind of weird ways.

**Comment by grp** [comment]
With a non-retaining observer, you have to take care to tear it down yourself safely.

There's no way to support both weak references to the owning object and the observed object. One of them must be strong in order to give the observation a lifetime. If you make both non-retained, the lifecycle management becomes manual.

**Comment by pronebird** [comment]
@grp I see that, and doing unobserveAll in dealloc does not work because it's too late
