### ISSUE TITLE
Project connot build, how to fix that?

### ISSUE THREAD

**Issue by Lingyj** [facebook/KVOController#65]
Error info like this:

Undefined symbols for architecture arm64:
  "_llvm_gcov_init", referenced from:
      ___llvm_gcov_init in libFBKVOController.a(NSObject+FBKVOController.o)
      ___llvm_gcov_init in libFBKVOController.a(FBKVOController.o)
  "_llvm_gcda_end_file", referenced from:
      ___llvm_gcov_writeout in libFBKVOController.a(NSObject+FBKVOController.o)
      ___llvm_gcov_writeout in libFBKVOController.a(FBKVOController.o)
  "_llvm_gcda_emit_function", referenced from:
      ___llvm_gcov_writeout in libFBKVOController.a(NSObject+FBKVOController.o)
      ___llvm_gcov_writeout in libFBKVOController.a(FBKVOController.o)
  "_llvm_gcda_emit_arcs", referenced from:
      ___llvm_gcov_writeout in libFBKVOController.a(NSObject+FBKVOController.o)
      ___llvm_gcov_writeout in libFBKVOController.a(FBKVOController.o)
  "_llvm_gcda_start_file", referenced from:
      ___llvm_gcov_writeout in libFBKVOController.a(NSObject+FBKVOController.o)
      ___llvm_gcov_writeout in libFBKVOController.a(FBKVOController.o)
  "_llvm_gcda_summary_info", referenced from:
      ___llvm_gcov_writeout in libFBKVOController.a(NSObject+FBKVOController.o)
      ___llvm_gcov_writeout in libFBKVOController.a(FBKVOController.o)

**Comment by grp** [comment]
@modocache — looks like this is probably because you turned on `GCC_GENERATE_TEST_COVERAGE_FILES` for the `Debug` and `Release` configurations rather than just a code coverage one?

**Comment by ewanmellor** [comment]
This has been caused by the following changeset.  `GCC_GENERATE_TEST_COVERAGE_FILES` and `GCC_INSTRUMENT_PROGRAM_FLOW_ARCS` have been turned on for all build configurations.

```
commit dc4c90de6e6eee6632d55acb71ea2ad227121a9b
Author: Brian Gesiak <bgesiak@fb.com>
Date:   Sat Apr 18 11:26:21 2015 -0400

    Generate coverage stats using slather/Coveralls

    - Modify project file to generate code coverage metrics
    - Add step to .travis.yml to install slather and send metrics to
      Coveralls
    - Add .slather.yml to configure how we send metrics to Coveralls.
    - Update Podfile.lock by running `pod install`.
```

**Comment by facebook-github-bot-7** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by ewanmellor** [comment]
Pinging @modocache

**Comment by bing5** [comment]
I have the issue

**Comment by modocache** [comment]
As @grp said I have a feeling this is due to the fact that slather turned coverage on for all schemes; see: https://github.com/venmo/slather/issues/73

Can someone confirm under what circumstances they see the error? The CI build is green, and the project builds for me locally, so are you experiencing failures...

- ...when building for device?
- ...when building with a Release configuration?

**Comment by ewanmellor** [comment]
@modocache Debug build for iPhone 4s sim on Xcode 6.4 (though I suspect other combinations will do exactly the same).  Depend upon target FBKVOController from FBKVOController.xcodeproj using Build Phases > Target Dependencies.  Link libFBKVOController.a using Build Phases > Link Binary With Libraries.  The link fails because libFBKVOController.a is using gcov.

It is conventional to only use coverage with a specific configuration, i.e. not in the normal debug or production builds, because of this problem (and because it slows down compilation significantly).

**Comment by modocache** [comment]
Thanks for the reports, everyone, and sorry for any inconvenience! This should be fixed now. If not, please create another issue. :wave:
